# Generated by Django 4.2.1 on 2023-05-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_country_alter_address_options_book_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='country',
            new_name='published_countries',
        ),
    ]
